name: Bump Minor Version

on:
  workflow_dispatch:
    inputs:
      commit-message:
        description: 'Commit message for version bump'
        required: true
        default: 'Bump minor version'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      
      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Bump Minor Version
        run: |
          # Read current version
          VERSION_FILE="lib/reportable_rails/version.rb"
          CURRENT_VERSION=$(grep -oP 'VERSION = "\K[0-9]+\.[0-9]+\.[0-9]+' "$VERSION_FILE")
          echo "Current version: $CURRENT_VERSION"
          
          # Split version into parts
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          
          # Increment minor version and reset patch
          NEW_VERSION="${MAJOR}.$((MINOR + 1)).0"
          echo "New version: $NEW_VERSION"
          
          # Update version.rb
          sed -i "s/VERSION = \"${CURRENT_VERSION}\"/VERSION = \"${NEW_VERSION}\"/" "$VERSION_FILE"
      
      - name: Commit and Push
        run: |
          git add lib/reportable_rails/version.rb
          git commit -m "${{ github.event.inputs.commit-message }} (${NEW_VERSION})"
          git push
