name: Create Release

on:
  push:
    branches: [ main, master ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Get version from version.rb
      id: get_version
      run: |
        VERSION=$(ruby -e "require './lib/reportable_rails/version.rb'; puts ReportableRails::VERSION")
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          LICENSE
          README.md
          reportable_rails-${{ steps.get_version.outputs.version }}.gem
