name: Create Release and Publish

on:
  workflow_dispatch: # allow repo collaborators to publish gem

permissions:
  contents: write # required for `rake release` to push the release tag
  id-token: write # required for workflow to publish gem

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # required to run `rake release`.
      - name: Setup Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          # setup-ruby implicitly uses .ruby-version
          bundler-cache: true
          rubygems: latest

      # Run `rake release` to create git tag and push to repository based on `lib/rpush/version.rb`.
      # Then publish the new gem via trusted publishing
      # Read more on https://guides.rubygems.org/trusted-publishing/releasing-gems/
      - name: Publish gem
        uses: rubygems/release-gem@v1


      - name: Get version from version.rb
        id: get_version
        run: |
          VERSION=$(ruby -e "require './lib/reportable_rails/version.rb'; puts ReportableRails::VERSION")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            LICENSE
            README.md
            reportable_rails-${{ steps.get_version.outputs.version }}.gem